---
vault.settings:
  type: config_object
  label: 'Vault'
  mapping:
    base_url:
      type: string
      label: 'Base URL'
    plugin_auth:
      type: string
      label: 'Authentication Plugin'
    lease_ttl_increment:
      type: string
      label: "Lease TTL Increment"
